// Thai address data structure
export interface Subdistrict {
  name: string;
  postalCode: string;
}

export interface District {
  name: string;
  subdistricts: Subdistrict[];
}

export interface Province {
  name: string;
  districts: District[];
}

// Simplified Thai address data (major provinces with sample districts)
export const thaiAddressData: Province[] = [
  {
    name: 'กรุงเทพมหานคร',
    districts: [
      {
        name: 'พระนคร',
        subdistricts: [
          { name: 'พระบรมมหาราชวัง', postalCode: '10200' },
          { name: 'วังบูรพาภิรมย์', postalCode: '10200' },
          { name: 'วัดราชบพิธ', postalCode: '10200' },
          { name: 'สำราญราษฎร์', postalCode: '10200' },
          { name: 'ศาลเจ้าพ่อเสือ', postalCode: '10200' },
          { name: 'เสาชิงช้า', postalCode: '10200' },
          { name: 'บวรนิเวศ', postalCode: '10200' },
          { name: 'ตลาดยอด', postalCode: '10200' },
          { name: 'ชนะสงคราม', postalCode: '10200' },
          { name: 'บ้านพานถม', postalCode: '10200' },
          { name: 'บางขุนพรหม', postalCode: '10200' },
          { name: 'วัดสามพระยา', postalCode: '10200' },
        ],
      },
      {
        name: 'ดุสิต',
        subdistricts: [
          { name: 'ดุสิต', postalCode: '10300' },
          { name: 'วชิรพยาบาล', postalCode: '10300' },
          { name: 'สวนจิตรลดา', postalCode: '10300' },
          { name: 'สี่แยกมหานาค', postalCode: '10300' },
          { name: 'ถนนนครไชยศรี', postalCode: '10300' },
        ],
      },
      {
        name: 'หนองจอก',
        subdistricts: [
          { name: 'กระทุ่มราย', postalCode: '10530' },
          { name: 'หนองจอก', postalCode: '10530' },
          { name: 'คลองสิบ', postalCode: '10530' },
          { name: 'คลองสิบสอง', postalCode: '10530' },
          { name: 'โคกแฝด', postalCode: '10530' },
          { name: 'คู้ฝั่งเหนือ', postalCode: '10530' },
          { name: 'ลำผักชี', postalCode: '10530' },
          { name: 'ลำต้อยติ่ง', postalCode: '10530' },
        ],
      },
      {
        name: 'บางรัก',
        subdistricts: [
          { name: 'มหาพฤฒาราม', postalCode: '10500' },
          { name: 'สีลม', postalCode: '10500' },
          { name: 'สุริยวงศ์', postalCode: '10500' },
          { name: 'บางรัก', postalCode: '10500' },
          { name: 'สี่พระยา', postalCode: '10500' },
        ],
      },
      {
        name: 'บางเขน',
        subdistricts: [
          { name: 'อนุสาวรีย์', postalCode: '10220' },
          { name: 'ท่าแร้ง', postalCode: '10220' },
        ],
      },
      {
        name: 'บางกะปิ',
        subdistricts: [
          { name: 'คลองจั่น', postalCode: '10240' },
          { name: 'หัวหมาก', postalCode: '10240' },
        ],
      },
      {
        name: 'ปทุมวัน',
        subdistricts: [
          { name: 'รองเมือง', postalCode: '10330' },
          { name: 'วังใหม่', postalCode: '10330' },
          { name: 'ปทุมวัน', postalCode: '10330' },
          { name: 'ลุมพินี', postalCode: '10330' },
        ],
      },
      {
        name: 'ป้อมปราบศัตรูพ่าย',
        subdistricts: [
          { name: 'ป้อมปราบ', postalCode: '10100' },
          { name: 'วัดเทพศิรินทร์', postalCode: '10100' },
          { name: 'คลองมหานาค', postalCode: '10100' },
          { name: 'บ้านบาตร', postalCode: '10100' },
          { name: 'วัดโสมนัส', postalCode: '10100' },
        ],
      },
      {
        name: 'พระโขนง',
        subdistricts: [
          { name: 'บางจาก', postalCode: '10260' },
        ],
      },
      {
        name: 'มีนบุรี',
        subdistricts: [
          { name: 'มีนบุรี', postalCode: '10510' },
          { name: 'แสนแสบ', postalCode: '10510' },
        ],
      },
      {
        name: 'ลาดกระบัง',
        subdistricts: [
          { name: 'ลาดกระบัง', postalCode: '10520' },
          { name: 'คลองสองต้นนุ่น', postalCode: '10520' },
          { name: 'คลองสามประเวศ', postalCode: '10520' },
          { name: 'ลำปลาทิว', postalCode: '10520' },
          { name: 'ทับยาว', postalCode: '10520' },
          { name: 'ขุมทอง', postalCode: '10520' },
        ],
      },
      {
        name: 'ยานนาวา',
        subdistricts: [
          { name: 'ช่องนนทรี', postalCode: '10120' },
          { name: 'บางโพงพาง', postalCode: '10120' },
        ],
      },
      {
        name: 'สัมพันธวงศ์',
        subdistricts: [
          { name: 'จักรวรรดิ', postalCode: '10100' },
          { name: 'สัมพันธวงศ์', postalCode: '10100' },
          { name: 'ตลาดน้อย', postalCode: '10100' },
        ],
      },
      {
        name: 'พญาไท',
        subdistricts: [
          { name: 'สามเสนใน', postalCode: '10400' },
          { name: 'พญาไท', postalCode: '10400' },
        ],
      },
      {
        name: 'ธนบุรี',
        subdistricts: [
          { name: 'วัดกัลยาณ์', postalCode: '10600' },
          { name: 'หิรัญรูจี', postalCode: '10600' },
          { name: 'บางยี่เรือ', postalCode: '10600' },
          { name: 'บุคคโล', postalCode: '10600' },
          { name: 'ตลาดพลู', postalCode: '10600' },
          { name: 'ดาวคะนอง', postalCode: '10600' },
          { name: 'สำเหร่', postalCode: '10600' },
        ],
      },
      {
        name: 'บางกอกใหญ่',
        subdistricts: [
          { name: 'วัดอรุณ', postalCode: '10600' },
          { name: 'วัดท่าพระ', postalCode: '10600' },
        ],
      },
      {
        name: 'ห้วยขวาง',
        subdistricts: [
          { name: 'ห้วยขวาง', postalCode: '10310' },
          { name: 'บางกะปิ', postalCode: '10310' },
          { name: 'สามเสนนอก', postalCode: '10310' },
        ],
      },
      {
        name: 'คลองสาน',
        subdistricts: [
          { name: 'สมเด็จเจ้าพระยา', postalCode: '10600' },
          { name: 'คลองสาน', postalCode: '10600' },
          { name: 'บางลำภูล่าง', postalCode: '10600' },
          { name: 'คลองต้นไทร', postalCode: '10600' },
        ],
      },
      {
        name: 'ตลิ่งชัน',
        subdistricts: [
          { name: 'คลองชักพระ', postalCode: '10170' },
          { name: 'ตลิ่งชัน', postalCode: '10170' },
          { name: 'ฉิมพลี', postalCode: '10170' },
          { name: 'บางพรม', postalCode: '10170' },
          { name: 'บางระมาด', postalCode: '10170' },
          { name: 'บางเชือกหนัง', postalCode: '10170' },
        ],
      },
      {
        name: 'บางกอกน้อย',
        subdistricts: [
          { name: 'ศิริราช', postalCode: '10700' },
          { name: 'บ้านช่างหล่อ', postalCode: '10700' },
          { name: 'บางขุนนนท์', postalCode: '10700' },
          { name: 'บางขุนศรี', postalCode: '10700' },
          { name: 'อรุณอมรินทร์', postalCode: '10700' },
        ],
      },
      {
        name: 'บางขุนเทียน',
        subdistricts: [
          { name: 'ท่าข้าม', postalCode: '10150' },
          { name: 'แสมดำ', postalCode: '10150' },
        ],
      },
      {
        name: 'ภาษีเจริญ',
        subdistricts: [
          { name: 'บางหว้า', postalCode: '10160' },
          { name: 'บางด้วน', postalCode: '10160' },
          { name: 'บางจาก', postalCode: '10160' },
          { name: 'บางแวก', postalCode: '10160' },
          { name: 'คลองขวาง', postalCode: '10160' },
          { name: 'ปากคลองภาษีเจริญ', postalCode: '10160' },
          { name: 'คูหาสวรรค์', postalCode: '10160' },
        ],
      },
      {
        name: 'หนองแขม',
        subdistricts: [
          { name: 'หนองแขม', postalCode: '10160' },
          { name: 'หนองค้างพลู', postalCode: '10160' },
        ],
      },
      {
        name: 'ราษฎร์บูรณะ',
        subdistricts: [
          { name: 'ราษฎร์บูรณะ', postalCode: '10140' },
          { name: 'บางปะกอก', postalCode: '10140' },
        ],
      },
      {
        name: 'บางพลัด',
        subdistricts: [
          { name: 'บางพลัด', postalCode: '10700' },
          { name: 'บางอ้อ', postalCode: '10700' },
          { name: 'บางบำหรุ', postalCode: '10700' },
          { name: 'บางยี่ขัน', postalCode: '10700' },
        ],
      },
      {
        name: 'ดินแดง',
        subdistricts: [
          { name: 'ดินแดง', postalCode: '10400' },
        ],
      },
      {
        name: 'บึงกุ่ม',
        subdistricts: [
          { name: 'คลองกุ่ม', postalCode: '10230' },
          { name: 'นวมินทร์', postalCode: '10230' },
          { name: 'นวลจันทร์', postalCode: '10230' },
        ],
      },
      {
        name: 'สาทร',
        subdistricts: [
          { name: 'ทุ่งวัดดอน', postalCode: '10120' },
          { name: 'ยานนาวา', postalCode: '10120' },
          { name: 'ทุ่งมหาเมฆ', postalCode: '10120' },
        ],
      },
      {
        name: 'บางซื่อ',
        subdistricts: [
          { name: 'บางซื่อ', postalCode: '10800' },
        ],
      },
      {
        name: 'จตุจักร',
        subdistricts: [
          { name: 'ลาดยาว', postalCode: '10900' },
          { name: 'เสนานิคม', postalCode: '10900' },
          { name: 'จันทรเกษม', postalCode: '10900' },
          { name: 'จอมพล', postalCode: '10900' },
          { name: 'จตุจักร', postalCode: '10900' },
        ],
      },
      {
        name: 'บางคอแหลม',
        subdistricts: [
          { name: 'บางคอแหลม', postalCode: '10120' },
          { name: 'วัดพระยาไกร', postalCode: '10120' },
          { name: 'บางโคล่', postalCode: '10120' },
        ],
      },
      {
        name: 'ประเวศ',
        subdistricts: [
          { name: 'ประเวศ', postalCode: '10250' },
          { name: 'หนองบอน', postalCode: '10250' },
          { name: 'ดอกไม้', postalCode: '10250' },
          { name: 'สวนหลวง', postalCode: '10250' },
        ],
      },
      {
        name: 'คลองเตย',
        subdistricts: [
          { name: 'คลองเตย', postalCode: '10110' },
          { name: 'คลองตัน', postalCode: '10110' },
          { name: 'พระโขนง', postalCode: '10110' },
          { name: 'คลองเตยเหนือ', postalCode: '10110' },
        ],
      },
      {
        name: 'สวนหลวง',
        subdistricts: [
          { name: 'สวนหลวง', postalCode: '10250' },
          { name: 'อ่อนนุช', postalCode: '10250' },
          { name: 'พัฒนาการ', postalCode: '10250' },
        ],
      },
      {
        name: 'จอมทอง',
        subdistricts: [
          { name: 'บางขุนเทียน', postalCode: '10150' },
          { name: 'บางค้อ', postalCode: '10150' },
          { name: 'บางมด', postalCode: '10150' },
          { name: 'จอมทอง', postalCode: '10150' },
        ],
      },
      {
        name: 'ดอนเมือง',
        subdistricts: [
          { name: 'สีกัน', postalCode: '10210' },
          { name: 'ดอนเมือง', postalCode: '10210' },
          { name: 'สนามบิน', postalCode: '10210' },
        ],
      },
      {
        name: 'ราชเทวี',
        subdistricts: [
          { name: 'ทุ่งพญาไท', postalCode: '10400' },
          { name: 'ถนนพญาไท', postalCode: '10400' },
          { name: 'ถนนเพชรบุรี', postalCode: '10400' },
          { name: 'มักกะสัน', postalCode: '10400' },
        ],
      },
      {
        name: 'ลาดพร้าว',
        subdistricts: [
          { name: 'ลาดพร้าว', postalCode: '10230' },
          { name: 'จรเข้บัว', postalCode: '10230' },
        ],
      },
      {
        name: 'วัฒนา',
        subdistricts: [
          { name: 'คลองเตยเหนือ', postalCode: '10110' },
          { name: 'คลองตันเหนือ', postalCode: '10110' },
          { name: 'พระโขนงเหนือ', postalCode: '10110' },
        ],
      },
      {
        name: 'บางแค',
        subdistricts: [
          { name: 'บางแค', postalCode: '10160' },
          { name: 'บางแคเหนือ', postalCode: '10160' },
          { name: 'บางไผ่', postalCode: '10160' },
          { name: 'หลักสอง', postalCode: '10160' },
        ],
      },
      {
        name: 'หลักสี่',
        subdistricts: [
          { name: 'ทุ่งสองห้อง', postalCode: '10210' },
          { name: 'ตลาดบางเขน', postalCode: '10210' },
        ],
      },
      {
        name: 'สายไหม',
        subdistricts: [
          { name: 'สายไหม', postalCode: '10220' },
          { name: 'ออเงิน', postalCode: '10220' },
          { name: 'คลองถนน', postalCode: '10220' },
        ],
      },
      {
        name: 'คันนายาว',
        subdistricts: [
          { name: 'คันนายาว', postalCode: '10230' },
          { name: 'รามอินทรา', postalCode: '10230' },
        ],
      },
      {
        name: 'สะพานสูง',
        subdistricts: [
          { name: 'สะพานสูง', postalCode: '10240' },
        ],
      },
      {
        name: 'วังทองหลาง',
        subdistricts: [
          { name: 'วังทองหลาง', postalCode: '10310' },
          { name: 'สะพานสอง', postalCode: '10310' },
          { name: 'คลองเจ้าคุณสิงห์', postalCode: '10310' },
          { name: 'พลับพลา', postalCode: '10310' },
        ],
      },
      {
        name: 'คลองสามวา',
        subdistricts: [
          { name: 'สามวาตะวันตก', postalCode: '10510' },
          { name: 'สามวาตะวันออก', postalCode: '10510' },
          { name: 'บางชัน', postalCode: '10510' },
          { name: 'ทรายกองดิน', postalCode: '10510' },
          { name: 'ทรายกองดินใต้', postalCode: '10510' },
        ],
      },
      {
        name: 'บางนา',
        subdistricts: [
          { name: 'บางนา', postalCode: '10260' },
        ],
      },
      {
        name: 'ทวีวัฒนา',
        subdistricts: [
          { name: 'ทวีวัฒนา', postalCode: '10170' },
          { name: 'ศาลาธรรมสพน์', postalCode: '10170' },
        ],
      },
      {
        name: 'ทุ่งครุ',
        subdistricts: [
          { name: 'บางมด', postalCode: '10140' },
          { name: 'ทุ่งครุ', postalCode: '10140' },
        ],
      },
      {
        name: 'บางบอน',
        subdistricts: [
          { name: 'บางบอน', postalCode: '10150' },
        ],
      },
    ],
  },
  {
    name: 'เชียงใหม่',
    districts: [
      {
        name: 'เมืองเชียงใหม่',
        subdistricts: [
          { name: 'ศรีภูมิ', postalCode: '50200' },
          { name: 'พระสิงห์', postalCode: '50200' },
          { name: 'หายยา', postalCode: '50100' },
          { name: 'ช้างม่อย', postalCode: '50300' },
          { name: 'ช้างคลาน', postalCode: '50100' },
          { name: 'วัดเกต', postalCode: '50000' },
          { name: 'ช้างเผือก', postalCode: '50300' },
          { name: 'สุเทพ', postalCode: '50200' },
          { name: 'แม่เหียะ', postalCode: '50100' },
          { name: 'ป่าแดด', postalCode: '50100' },
          { name: 'หนองหอย', postalCode: '50000' },
          { name: 'ท่าศาลา', postalCode: '50000' },
          { name: 'หนองป่าครั่ง', postalCode: '50000' },
          { name: 'ฟ้าฮ่าม', postalCode: '50000' },
          { name: 'ป่าตัน', postalCode: '50300' },
          { name: 'สันผีเสื้อ', postalCode: '50300' },
        ],
      },
      {
        name: 'จอมทอง',
        subdistricts: [
          { name: 'บ้านหลวง', postalCode: '50160' },
          { name: 'ข่วงเปา', postalCode: '50160' },
          { name: 'สบเตี๊ยะ', postalCode: '50160' },
          { name: 'บ้านแปะ', postalCode: '50240' },
          { name: 'ดอยแก้ว', postalCode: '50160' },
          { name: 'แม่สอย', postalCode: '50240' },
        ],
      },
      {
        name: 'แม่แจ่ม',
        subdistricts: [
          { name: 'ช่างเคิ่ง', postalCode: '50270' },
          { name: 'ท่าผา', postalCode: '50270' },
          { name: 'บ้านทับ', postalCode: '50270' },
          { name: 'แม่ศึก', postalCode: '50270' },
          { name: 'แม่นาจร', postalCode: '50270' },
          { name: 'ปางหินฝน', postalCode: '50270' },
          { name: 'กองแขก', postalCode: '50270' },
        ],
      },
      {
        name: 'เชียงดาว',
        subdistricts: [
          { name: 'เชียงดาว', postalCode: '50170' },
          { name: 'เมืองนะ', postalCode: '50170' },
          { name: 'เมืองงาย', postalCode: '50170' },
          { name: 'แม่นะ', postalCode: '50170' },
          { name: 'เมืองคอง', postalCode: '50170' },
          { name: 'ปิงโค้ง', postalCode: '50170' },
          { name: 'ทุ่งข้าวพวง', postalCode: '50170' },
        ],
      },
      {
        name: 'ดอยสะเก็ด',
        subdistricts: [
          { name: 'เชิงดอย', postalCode: '50220' },
          { name: 'สันปูเลย', postalCode: '50220' },
          { name: 'ลวงเหนือ', postalCode: '50220' },
          { name: 'ป่าเมี่ยง', postalCode: '50220' },
          { name: 'สง่าบ้าน', postalCode: '50220' },
          { name: 'ป่าลาน', postalCode: '50220' },
          { name: 'ตลาดขวัญ', postalCode: '50220' },
          { name: 'สำราญราษฎร์', postalCode: '50220' },
          { name: 'แม่คือ', postalCode: '50220' },
          { name: 'ตลาดใหญ่', postalCode: '50220' },
          { name: 'แม่ฮ้อยเงิน', postalCode: '50220' },
          { name: 'แม่โป่ง', postalCode: '50220' },
          { name: 'ป่าป้อง', postalCode: '50220' },
          { name: 'เทพเสด็จ', postalCode: '50220' },
        ],
      },
      {
        name: 'แม่แตง',
        subdistricts: [
          { name: 'สันมหาพน', postalCode: '50150' },
          { name: 'แม่แตง', postalCode: '50150' },
          { name: 'ขี้เหล็ก', postalCode: '50150' },
          { name: 'ช่อแล', postalCode: '50150' },
          { name: 'แม่หอพระ', postalCode: '50150' },
          { name: 'สบเปิง', postalCode: '50150' },
          { name: 'บ้านเป้า', postalCode: '50150' },
          { name: 'สันป่ายาง', postalCode: '50330' },
          { name: 'ป่าแป๋', postalCode: '50150' },
          { name: 'เมืองก๋าย', postalCode: '50150' },
          { name: 'บ้านช้าง', postalCode: '50150' },
          { name: 'กื้ดช้าง', postalCode: '50150' },
          { name: 'อินทขิล', postalCode: '50150' },
        ],
      },
      {
        name: 'แม่ริม',
        subdistricts: [
          { name: 'ริมใต้', postalCode: '50180' },
          { name: 'ริมเหนือ', postalCode: '50180' },
          { name: 'สันโป่ง', postalCode: '50180' },
          { name: 'ขี้เหล็ก', postalCode: '50180' },
          { name: 'สะลวง', postalCode: '50330' },
          { name: 'ห้วยทราย', postalCode: '50180' },
          { name: 'แม่แรม', postalCode: '50180' },
          { name: 'โป่งแยง', postalCode: '50180' },
          { name: 'แม่สา', postalCode: '50180' },
          { name: 'ดอนแก้ว', postalCode: '50180' },
          { name: 'เหมืองแก้ว', postalCode: '50180' },
        ],
      },
      {
        name: 'สะเมิง',
        subdistricts: [
          { name: 'สะเมิงใต้', postalCode: '50250' },
          { name: 'สะเมิงเหนือ', postalCode: '50250' },
          { name: 'แม่สาบ', postalCode: '50250' },
          { name: 'บ่อแก้ว', postalCode: '50250' },
          { name: 'ยั้งเมิน', postalCode: '50250' },
        ],
      },
      {
        name: 'ฝาง',
        subdistricts: [
          { name: 'เวียง', postalCode: '50110' },
          { name: 'ม่อนปิ่น', postalCode: '50110' },
          { name: 'แม่งอน', postalCode: '50320' },
          { name: 'แม่สูน', postalCode: '50110' },
          { name: 'สันทราย', postalCode: '50110' },
          { name: 'แม่คะ', postalCode: '50110' },
          { name: 'แม่ข่า', postalCode: '50320' },
          { name: 'โป่งน้ำร้อน', postalCode: '50110' },
        ],
      },
      {
        name: 'แม่อาย',
        subdistricts: [
          { name: 'แม่อาย', postalCode: '50280' },
          { name: 'แม่สาว', postalCode: '50280' },
          { name: 'สันต้นหมื้อ', postalCode: '50280' },
          { name: 'แม่นาวาง', postalCode: '50280' },
          { name: 'ท่าตอน', postalCode: '50280' },
          { name: 'บ้านหลวง', postalCode: '50280' },
          { name: 'มะลิกา', postalCode: '50280' },
        ],
      },
      {
        name: 'พร้าว',
        subdistricts: [
          { name: 'เวียง', postalCode: '50190' },
          { name: 'ทุ่งหลวง', postalCode: '50190' },
          { name: 'ป่าตุ้ม', postalCode: '50190' },
          { name: 'ป่าไหน่', postalCode: '50190' },
          { name: 'สันทราย', postalCode: '50190' },
          { name: 'บ้านโป่ง', postalCode: '50190' },
          { name: 'น้ำแพร่', postalCode: '50190' },
          { name: 'เขื่อนผาก', postalCode: '50190' },
          { name: 'แม่แวน', postalCode: '50190' },
          { name: 'แม่ปั๋ง', postalCode: '50190' },
          { name: 'โหล่งขอด', postalCode: '50190' },
        ],
      },
      {
        name: 'สันป่าตอง',
        subdistricts: [
          { name: 'ยุหว่า', postalCode: '50120' },
          { name: 'สันกลาง', postalCode: '50120' },
          { name: 'ท่าวังพร้าว', postalCode: '50120' },
          { name: 'มะขามหลวง', postalCode: '50120' },
          { name: 'แม่ก๊า', postalCode: '50120' },
          { name: 'บ้านแม', postalCode: '50120' },
          { name: 'บ้านกลาง', postalCode: '50120' },
          { name: 'ทุ่งสะโตก', postalCode: '50120' },
          { name: 'ทุ่งต้อม', postalCode: '50120' },
          { name: 'น้ำบ่อหลวง', postalCode: '50120' },
          { name: 'มะขุนหวาน', postalCode: '50120' },
        ],
      },
      {
        name: 'สันกำแพง',
        subdistricts: [
          { name: 'สันกำแพง', postalCode: '50130' },
          { name: 'ทรายมูล', postalCode: '50130' },
          { name: 'ร้องวัวแดง', postalCode: '50130' },
          { name: 'บวกค้าง', postalCode: '50130' },
          { name: 'แช่ช้าง', postalCode: '50130' },
          { name: 'ออนใต้', postalCode: '50130' },
          { name: 'แม่ปูคา', postalCode: '50130' },
          { name: 'ห้วยทราย', postalCode: '50130' },
          { name: 'ต้นเปา', postalCode: '50130' },
          { name: 'สันกลาง', postalCode: '50130' },
        ],
      },
      {
        name: 'สันทราย',
        subdistricts: [
          { name: 'สันทรายหลวง', postalCode: '50210' },
          { name: 'สันทรายน้อย', postalCode: '50210' },
          { name: 'สันพระเนตร', postalCode: '50210' },
          { name: 'สันนาเม็ง', postalCode: '50210' },
          { name: 'สันป่าเปา', postalCode: '50210' },
          { name: 'หนองแหย่ง', postalCode: '50210' },
          { name: 'หนองจ๊อม', postalCode: '50210' },
          { name: 'หนองหาร', postalCode: '50290' },
          { name: 'แม่แฝก', postalCode: '50290' },
          { name: 'แม่แฝกใหม่', postalCode: '50290' },
          { name: 'เมืองเล็น', postalCode: '50210' },
          { name: 'ป่าไผ่', postalCode: '50210' },
        ],
      },
      {
        name: 'หางดง',
        subdistricts: [
          { name: 'หางดง', postalCode: '50230' },
          { name: 'หนองแก๋ว', postalCode: '50230' },
          { name: 'หารแก้ว', postalCode: '50230' },
          { name: 'หนองตอง', postalCode: '50340' },
          { name: 'ขุนคง', postalCode: '50230' },
          { name: 'สบแม่ข่า', postalCode: '50230' },
          { name: 'บ้านแหวน', postalCode: '50230' },
          { name: 'สันผักหวาน', postalCode: '50230' },
          { name: 'หนองควาย', postalCode: '50230' },
          { name: 'บ้านปง', postalCode: '50230' },
          { name: 'น้ำแพร่', postalCode: '50230' },
        ],
      },
      {
        name: 'ฮอด',
        subdistricts: [
          { name: 'หางดง', postalCode: '50240' },
          { name: 'ฮอด', postalCode: '50240' },
          { name: 'บ้านตาล', postalCode: '50240' },
          { name: 'บ่อหลวง', postalCode: '50240' },
          { name: 'บ่อสลี', postalCode: '50240' },
          { name: 'นาคอเรือ', postalCode: '50240' },
        ],
      },
      {
        name: 'ดอยเต่า',
        subdistricts: [
          { name: 'ดอยเต่า', postalCode: '50260' },
          { name: 'ท่าเดื่อ', postalCode: '50260' },
          { name: 'มืดกา', postalCode: '50260' },
          { name: 'บ้านแอ่น', postalCode: '50260' },
          { name: 'บงตัน', postalCode: '50260' },
          { name: 'โปงทุ่ง', postalCode: '50260' },
        ],
      },
      {
        name: 'อมก๋อย',
        subdistricts: [
          { name: 'อมก๋อย', postalCode: '50310' },
          { name: 'ยางเปียง', postalCode: '50310' },
          { name: 'แม่ตื่น', postalCode: '50310' },
          { name: 'ม่อนจอง', postalCode: '50310' },
          { name: 'สบโขง', postalCode: '50310' },
          { name: 'นาเกียน', postalCode: '50310' },
        ],
      },
      {
        name: 'สารภี',
        subdistricts: [
          { name: 'ยางเนิ้ง', postalCode: '50140' },
          { name: 'สารภี', postalCode: '50140' },
          { name: 'ชมภู', postalCode: '50140' },
          { name: 'ไชยสถาน', postalCode: '50140' },
          { name: 'ขัวมุง', postalCode: '50140' },
          { name: 'หนองผึ้ง', postalCode: '50140' },
          { name: 'หนองแฝก', postalCode: '50140' },
          { name: 'ท่ากว้าง', postalCode: '50140' },
          { name: 'ดอนแก้ว', postalCode: '50140' },
          { name: 'ท่าวังตาล', postalCode: '50140' },
          { name: 'สันทราย', postalCode: '50140' },
          { name: 'ป่าบง', postalCode: '50140' },
        ],
      },
      {
        name: 'เวียงแหง',
        subdistricts: [
          { name: 'เมืองแหง', postalCode: '50350' },
          { name: 'เปียงหลวง', postalCode: '50350' },
          { name: 'แสนไห', postalCode: '50350' },
        ],
      },
      {
        name: 'ไชยปราการ',
        subdistricts: [
          { name: 'ปงตำ', postalCode: '50320' },
          { name: 'ศรีดงเย็น', postalCode: '50320' },
          { name: 'แม่ทะลบ', postalCode: '50320' },
          { name: 'หนองบัว', postalCode: '50320' },
        ],
      },
      {
        name: 'แม่วาง',
        subdistricts: [
          { name: 'บ้านกาด', postalCode: '50360' },
          { name: 'ทุ่งปี้', postalCode: '50360' },
          { name: 'ทุ่งรวงทอง', postalCode: '50360' },
          { name: 'แม่วิน', postalCode: '50360' },
          { name: 'ดอนเปา', postalCode: '50360' },
        ],
      },
      {
        name: 'แม่ออน',
        subdistricts: [
          { name: 'ออนเหนือ', postalCode: '50130' },
          { name: 'ออนกลาง', postalCode: '50130' },
          { name: 'บ้านสหกรณ์', postalCode: '50130' },
          { name: 'ห้วยแก้ว', postalCode: '50130' },
          { name: 'แม่ทา', postalCode: '50130' },
          { name: 'ทาเหนือ', postalCode: '50130' },
        ],
      },
      {
        name: 'ดอยหล่อ',
        subdistricts: [
          { name: 'ดอยหล่อ', postalCode: '50160' },
          { name: 'สองแคว', postalCode: '50160' },
          { name: 'ยางคราม', postalCode: '50160' },
          { name: 'สันติสุข', postalCode: '50160' },
        ],
      },
      {
        name: 'กัลยาณิวัฒนา',
        subdistricts: [
          { name: 'บ้านจันทร์', postalCode: '58130' },
          { name: 'แม่แดด', postalCode: '58130' },
          { name: 'แจ่มหลวง', postalCode: '58130' },
        ],
      },
    ],
  },
  {
    name: 'นครราชสีมา',
    districts: [
      {
        name: 'เมืองนครราชสีมา',
        subdistricts: [
          { name: 'ในเมือง', postalCode: '30000' },
          { name: 'โพธิ์กลาง', postalCode: '30000' },
          { name: 'หนองจะบก', postalCode: '30000' },
          { name: 'โคกสูง', postalCode: '30310' },
          { name: 'มะเริง', postalCode: '30000' },
          { name: 'หนองระเวียง', postalCode: '30000' },
          { name: 'ปรุใหญ่', postalCode: '30000' },
          { name: 'หมื่นไวย', postalCode: '30000' },
          { name: 'พลกรัง', postalCode: '30000' },
          { name: 'หนองไผ่ล้อม', postalCode: '30000' },
          { name: 'บ้านเกาะ', postalCode: '30000' },
          { name: 'บ้านใหม่', postalCode: '30000' },
          { name: 'พุดซา', postalCode: '30000' },
          { name: 'บ้านโพธิ์', postalCode: '30310' },
          { name: 'จอหอ', postalCode: '30310' },
          { name: 'โคกกรวด', postalCode: '30280' },
          { name: 'ไชยมงคล', postalCode: '30000' },
          { name: 'หนองบัวศาลา', postalCode: '30000' },
          { name: 'สุรนารี', postalCode: '30000' },
          { name: 'สีมุม', postalCode: '30000' },
          { name: 'ตลาด', postalCode: '30310' },
          { name: 'พะเนา', postalCode: '30000' },
          { name: 'หนองกระทุ่ม', postalCode: '30000' },
          { name: 'หัวทะเล', postalCode: '30000' },
          { name: 'บ้านค่าย', postalCode: '30000' },
        ],
      },
      {
        name: 'ครบุรี',
        subdistricts: [
          { name: 'แชะ', postalCode: '30250' },
          { name: 'เฉลียง', postalCode: '30250' },
          { name: 'ครบุรี', postalCode: '30250' },
          { name: 'โคกกระชาย', postalCode: '30250' },
          { name: 'จระเข้หิน', postalCode: '30250' },
          { name: 'มาบตะโกเอน', postalCode: '30250' },
          { name: 'อรพิมพ์', postalCode: '30250' },
          { name: 'บ้านใหม่', postalCode: '30250' },
          { name: 'ลำเพียก', postalCode: '30250' },
          { name: 'ครบุรีใต้', postalCode: '30250' },
          { name: 'ตะแบกบาน', postalCode: '30250' },
          { name: 'สระว่านพระยา', postalCode: '30250' },
        ],
      },
      {
        name: 'เสิงสาง',
        subdistricts: [
          { name: 'เสิงสาง', postalCode: '30330' },
          { name: 'สระตะเคียน', postalCode: '30330' },
          { name: 'โนนสมบูรณ์', postalCode: '30330' },
          { name: 'กุดโบสถ์', postalCode: '30330' },
          { name: 'สุขไพบูลย์', postalCode: '30330' },
          { name: 'บ้านราษฎร์', postalCode: '30330' },
        ],
      },
      {
        name: 'คง',
        subdistricts: [
          { name: 'เมืองคง', postalCode: '30260' },
          { name: 'คูขาด', postalCode: '30260' },
          { name: 'เทพาลัย', postalCode: '30260' },
          { name: 'ตาจั่น', postalCode: '30260' },
          { name: 'บ้านปรางค์', postalCode: '30260' },
          { name: 'หนองมะนาว', postalCode: '30260' },
          { name: 'หนองบัว', postalCode: '30260' },
          { name: 'โนนเต็ง', postalCode: '30260' },
          { name: 'ดอนใหญ่', postalCode: '30260' },
          { name: 'ขามสมบูรณ์', postalCode: '30260' },
        ],
      },
      {
        name: 'บ้านเหลื่อม',
        subdistricts: [
          { name: 'บ้านเหลื่อม', postalCode: '30350' },
          { name: 'วังโพธิ์', postalCode: '30350' },
          { name: 'โคกกระเบื้อง', postalCode: '30350' },
          { name: 'ช่อระกา', postalCode: '30350' },
        ],
      },
      {
        name: 'จักราช',
        subdistricts: [
          { name: 'จักราช', postalCode: '30230' },
          { name: 'ท่าช้าง', postalCode: '30230' },
          { name: 'ทองหลาง', postalCode: '30230' },
          { name: 'สีสุก', postalCode: '30230' },
          { name: 'หนองขาม', postalCode: '30230' },
          { name: 'หนองพลวง', postalCode: '30230' },
          { name: 'ศรีละกอ', postalCode: '30230' },
          { name: 'คลองเมือง', postalCode: '30230' },
          { name: 'หินโคน', postalCode: '30230' },
        ],
      },
      {
        name: 'โชคชัย',
        subdistricts: [
          { name: 'กระโทก', postalCode: '30190' },
          { name: 'พลับพลา', postalCode: '30190' },
          { name: 'ท่าอ่าง', postalCode: '30190' },
          { name: 'ทุ่งอรุณ', postalCode: '30190' },
          { name: 'ท่าลาดขาว', postalCode: '30190' },
          { name: 'ท่าจะหลุง', postalCode: '30190' },
          { name: 'ท่าเยี่ยม', postalCode: '30190' },
          { name: 'โชคชัย', postalCode: '30190' },
          { name: 'ละลมใหม่พัฒนา', postalCode: '30190' },
          { name: 'ด่านเกวียน', postalCode: '30190' },
        ],
      },
      {
        name: 'ด่านขุนทด',
        subdistricts: [
          { name: 'กุดพิมาน', postalCode: '30210' },
          { name: 'ด่านขุนทด', postalCode: '30210' },
          { name: 'ด่านนอก', postalCode: '30210' },
          { name: 'ด่านใน', postalCode: '30210' },
          { name: 'ตะเคียน', postalCode: '30210' },
          { name: 'บ้านเก่า', postalCode: '30210' },
          { name: 'บ้านแปรง', postalCode: '30210' },
          { name: 'พันชนะ', postalCode: '30210' },
          { name: 'สระจรเข้', postalCode: '30210' },
          { name: 'หนองกราด', postalCode: '30210' },
          { name: 'หนองบัวตะเกียด', postalCode: '30210' },
          { name: 'หนองบัวละคร', postalCode: '30210' },
          { name: 'หินดาด', postalCode: '30210' },
          { name: 'ห้วยบง', postalCode: '30210' },
          { name: 'โนนเมืองพัฒนา', postalCode: '30210' },
          { name: 'หนองไทร', postalCode: '36220' },
        ],
      },
      {
        name: 'โนนไทย',
        subdistricts: [
          { name: 'โนนไทย', postalCode: '30220' },
          { name: 'ด่านจาก', postalCode: '30220' },
          { name: 'กำปัง', postalCode: '30220' },
          { name: 'สำโรง', postalCode: '30220' },
          { name: 'ค้างพลู', postalCode: '30220' },
          { name: 'บ้านวัง', postalCode: '30220' },
          { name: 'บัลลังก์', postalCode: '30220' },
          { name: 'สายออ', postalCode: '30220' },
          { name: 'ถนนโพธิ์', postalCode: '30220' },
          { name: 'พังเทียม', postalCode: '30220' },
          { name: 'มะค่า', postalCode: '30220' },
        ],
      },
      {
        name: 'โนนสูง',
        subdistricts: [
          { name: 'โนนสูง', postalCode: '30160' },
          { name: 'ใหม่', postalCode: '30160' },
          { name: 'โตนด', postalCode: '30160' },
          { name: 'บิง', postalCode: '30160' },
          { name: 'ดอนชมพู', postalCode: '30160' },
          { name: 'ธารปราสาท', postalCode: '30240' },
          { name: 'หลุมข้าว', postalCode: '30160' },
          { name: 'มะค่า', postalCode: '30160' },
          { name: 'พลสงคราม', postalCode: '30160' },
          { name: 'จันอัด', postalCode: '30160' },
          { name: 'ขามเฒ่า', postalCode: '30160' },
          { name: 'ด่านคล้า', postalCode: '30160' },
          { name: 'ลำคอหงษ์', postalCode: '30160' },
          { name: 'เมืองปราสาท', postalCode: '30160' },
          { name: 'ดอนหวาย', postalCode: '30160' },
          { name: 'ลำมูล', postalCode: '30160' },
        ],
      },
    ],
  },
  {
    name: 'ขอนแก่น',
    districts: [
      {
        name: 'เมืองขอนแก่น',
        subdistricts: [
          { name: 'ในเมือง', postalCode: '40000' },
          { name: 'สำราญ', postalCode: '40000' },
          { name: 'โคกสี', postalCode: '40000' },
          { name: 'ท่าพระ', postalCode: '40260' },
          { name: 'บ้านทุ่ม', postalCode: '40000' },
          { name: 'เมืองเก่า', postalCode: '40000' },
          { name: 'พระลับ', postalCode: '40000' },
          { name: 'สาวะถี', postalCode: '40000' },
          { name: 'บ้านหว้า', postalCode: '40000' },
          { name: 'บ้านค้อ', postalCode: '40000' },
          { name: 'แดงใหญ่', postalCode: '40000' },
          { name: 'ดอนช้าง', postalCode: '40000' },
          { name: 'ดอนหัน', postalCode: '40260' },
          { name: 'ศิลา', postalCode: '40000' },
          { name: 'บ้านเป็ด', postalCode: '40000' },
          { name: 'หนองตูม', postalCode: '40000' },
          { name: 'บึงเนียม', postalCode: '40000' },
          { name: 'โนนท่อน', postalCode: '40000' },
        ],
      },
      {
        name: 'บ้านฝาง',
        subdistricts: [
          { name: 'บ้านฝาง', postalCode: '40270' },
          { name: 'ป่ามะนาว', postalCode: '40270' },
          { name: 'โนนฆ้อง', postalCode: '40270' },
          { name: 'บ้านเหล่า', postalCode: '40270' },
          { name: 'ป่าหวายนั่ง', postalCode: '40270' },
          { name: 'โคกงาม', postalCode: '40270' },
          { name: 'หนองบัว', postalCode: '40270' },
        ],
      },
      {
        name: 'พระยืน',
        subdistricts: [
          { name: 'พระยืน', postalCode: '40320' },
          { name: 'พระบุ', postalCode: '40320' },
          { name: 'บ้านโต้น', postalCode: '40320' },
          { name: 'หนองแวง', postalCode: '40320' },
          { name: 'ขามป้อม', postalCode: '40320' },
        ],
      },
      {
        name: 'หนองเรือ',
        subdistricts: [
          { name: 'หนองเรือ', postalCode: '40210' },
          { name: 'บ้านเม็ง', postalCode: '40210' },
          { name: 'บ้านกง', postalCode: '40240' },
          { name: 'ยางคำ', postalCode: '40240' },
          { name: 'จระเข้', postalCode: '40240' },
          { name: 'โนนทอง', postalCode: '40210' },
          { name: 'กุดกว้าง', postalCode: '40210' },
          { name: 'โนนทัน', postalCode: '40210' },
          { name: 'โนนสะอาด', postalCode: '40210' },
          { name: 'บ้านผือ', postalCode: '40240' },
        ],
      },
      {
        name: 'ชุมแพ',
        subdistricts: [
          { name: 'ชุมแพ', postalCode: '40130' },
          { name: 'โนนหัน', postalCode: '40290' },
          { name: 'นาหนองทุ่ม', postalCode: '40290' },
          { name: 'โนนอุดม', postalCode: '40130' },
          { name: 'ขัวเรียง', postalCode: '40130' },
          { name: 'หนองไผ่', postalCode: '40130' },
          { name: 'ไชยสอ', postalCode: '40130' },
          { name: 'วังหินลาด', postalCode: '40130' },
          { name: 'นาเพียง', postalCode: '40130' },
          { name: 'หนองเขียด', postalCode: '40290' },
          { name: 'หนองเสาเล้า', postalCode: '40130' },
          { name: 'โนนสะอาด', postalCode: '40290' },
        ],
      },
      {
        name: 'สีชมพู',
        subdistricts: [
          { name: 'สีชมพู', postalCode: '40220' },
          { name: 'ศรีสุข', postalCode: '40220' },
          { name: 'นาจาน', postalCode: '40220' },
          { name: 'วังเพิ่ม', postalCode: '40220' },
          { name: 'ซำยาง', postalCode: '40220' },
          { name: 'หนองแดง', postalCode: '40220' },
          { name: 'ดงลาน', postalCode: '40220' },
          { name: 'บริบูรณ์', postalCode: '40220' },
          { name: 'บ้านใหม่', postalCode: '40220' },
          { name: 'ภูห่าน', postalCode: '40220' },
        ],
      },
      {
        name: 'น้ำพอง',
        subdistricts: [
          { name: 'น้ำพอง', postalCode: '40140' },
          { name: 'วังชัย', postalCode: '40140' },
          { name: 'หนองกุง', postalCode: '40140' },
          { name: 'บัวใหญ่', postalCode: '40140' },
          { name: 'สะอาด', postalCode: '40310' },
          { name: 'ม่วงหวาน', postalCode: '40310' },
          { name: 'บ้านขาม', postalCode: '40140' },
          { name: 'บัวเงิน', postalCode: '40140' },
          { name: 'ทรายมูล', postalCode: '40140' },
          { name: 'ท่ากระเสริม', postalCode: '40140' },
          { name: 'พังทุย', postalCode: '40140' },
          { name: 'กุดน้ำใส', postalCode: '40310' },
        ],
      },
      {
        name: 'อุบลรัตน์',
        subdistricts: [
          { name: 'โคกสูง', postalCode: '40250' },
          { name: 'บ้านดง', postalCode: '40250' },
          { name: 'เขื่อนอุบลรัตน์', postalCode: '40250' },
          { name: 'นาคำ', postalCode: '40250' },
          { name: 'ศรีสุขสำราญ', postalCode: '40250' },
          { name: 'ทุ่งโป่ง', postalCode: '40250' },
        ],
      },
      {
        name: 'กระนวน',
        subdistricts: [
          { name: 'หนองโก', postalCode: '40170' },
          { name: 'หนองกุงใหญ่', postalCode: '40170' },
          { name: 'ห้วยโจด', postalCode: '40170' },
          { name: 'ห้วยยาง', postalCode: '40170' },
          { name: 'บ้านฝาง', postalCode: '40170' },
          { name: 'ดูนสาด', postalCode: '40170' },
          { name: 'หนองโน', postalCode: '40170' },
          { name: 'น้ำอ้อม', postalCode: '40170' },
          { name: 'หัวนาคำ', postalCode: '40170' },
        ],
      },
      {
        name: 'บ้านไผ่',
        subdistricts: [
          { name: 'บ้านไผ่', postalCode: '40110' },
          { name: 'ในเมือง', postalCode: '40110' },
          { name: 'เมืองเพีย', postalCode: '40110' },
          { name: 'บ้านลาน', postalCode: '40110' },
          { name: 'แคนเหนือ', postalCode: '40110' },
          { name: 'ภูเหล็ก', postalCode: '40110' },
          { name: 'ป่าปอ', postalCode: '40110' },
          { name: 'หินตั้ง', postalCode: '40110' },
          { name: 'หนองน้ำใส', postalCode: '40110' },
          { name: 'หัวหนอง', postalCode: '40110' },
        ],
      },
    ],
  },
  {
    name: 'ชลบุรี',
    districts: [
      {
        name: 'เมืองชลบุรี',
        subdistricts: [
          { name: 'บางปลาสร้อย', postalCode: '20000' },
          { name: 'มะขามหย่ง', postalCode: '20000' },
          { name: 'บ้านโขด', postalCode: '20000' },
          { name: 'แสนสุข', postalCode: '20130' },
          { name: 'บ้านสวน', postalCode: '20000' },
          { name: 'หนองรี', postalCode: '20000' },
          { name: 'นาป่า', postalCode: '20000' },
          { name: 'หนองข้างคอก', postalCode: '20000' },
          { name: 'ดอนหัวฬ่อ', postalCode: '20000' },
          { name: 'หนองไม้แดง', postalCode: '20000' },
          { name: 'บางทราย', postalCode: '20000' },
          { name: 'คลองตำหรุ', postalCode: '20000' },
          { name: 'เหมือง', postalCode: '20130' },
          { name: 'บ้านปึก', postalCode: '20130' },
          { name: 'ห้วยกะปิ', postalCode: '20000' },
          { name: 'เสม็ด', postalCode: '20000' },
          { name: 'อ่างศิลา', postalCode: '20000' },
          { name: 'สำนักบก', postalCode: '20000' },
        ],
      },
      {
        name: 'บ้านบึง',
        subdistricts: [
          { name: 'บ้านบึง', postalCode: '20170' },
          { name: 'คลองกิ่ว', postalCode: '20220' },
          { name: 'มาบไผ่', postalCode: '20170' },
          { name: 'หนองซ้ำซาก', postalCode: '20170' },
          { name: 'หนองบอนแดง', postalCode: '20170' },
          { name: 'หนองชาก', postalCode: '20170' },
          { name: 'หนองอิรุณ', postalCode: '20220' },
          { name: 'หนองไผ่แก้ว', postalCode: '20220' },
        ],
      },
      {
        name: 'หนองใหญ่',
        subdistricts: [
          { name: 'หนองใหญ่', postalCode: '20190' },
          { name: 'คลองพลู', postalCode: '20190' },
          { name: 'หนองเสือช้าง', postalCode: '20190' },
          { name: 'ห้างสูง', postalCode: '20190' },
          { name: 'เขาซก', postalCode: '20190' },
        ],
      },
      {
        name: 'บางละมุง',
        subdistricts: [
          { name: 'บางละมุง', postalCode: '20150' },
          { name: 'หนองปรือ', postalCode: '20150' },
          { name: 'หนองปลาไหล', postalCode: '20150' },
          { name: 'โป่ง', postalCode: '20150' },
          { name: 'เขาไม้แก้ว', postalCode: '20150' },
          { name: 'ห้วยใหญ่', postalCode: '20150' },
          { name: 'ตะเคียนเตี้ย', postalCode: '20150' },
          { name: 'นาเกลือ', postalCode: '20150' },
        ],
      },
      {
        name: 'พานทอง',
        subdistricts: [
          { name: 'พานทอง', postalCode: '20160' },
          { name: 'หนองตำลึง', postalCode: '20160' },
          { name: 'มาบโป่ง', postalCode: '20160' },
          { name: 'หนองกะขะ', postalCode: '20160' },
          { name: 'หนองหงษ์', postalCode: '20160' },
          { name: 'โคกขี้หนอน', postalCode: '20160' },
          { name: 'บ้านเก่า', postalCode: '20160' },
          { name: 'หน้าประดู่', postalCode: '20160' },
          { name: 'บางนาง', postalCode: '20160' },
          { name: 'เกาะลอย', postalCode: '20160' },
          { name: 'บางหัก', postalCode: '20160' },
        ],
      },
      {
        name: 'พนัสนิคม',
        subdistricts: [
          { name: 'พนัสนิคม', postalCode: '20140' },
          { name: 'หน้าพระธาตุ', postalCode: '20140' },
          { name: 'วัดหลวง', postalCode: '20140' },
          { name: 'บ้านเซิด', postalCode: '20140' },
          { name: 'นาเริก', postalCode: '20140' },
          { name: 'หมอนนาง', postalCode: '20140' },
          { name: 'สระสี่เหลี่ยม', postalCode: '20140' },
          { name: 'วัดโบสถ์', postalCode: '20140' },
          { name: 'กุฎโง้ง', postalCode: '20140' },
          { name: 'หัวถนน', postalCode: '20140' },
          { name: 'ท่าข้าม', postalCode: '20140' },
          { name: 'หนองปรือ', postalCode: '20140' },
          { name: 'หนองขยาด', postalCode: '20140' },
          { name: 'ทุ่งขวาง', postalCode: '20140' },
          { name: 'หนองเหียง', postalCode: '20140' },
          { name: 'นาวังหิน', postalCode: '20140' },
          { name: 'บ้านช้าง', postalCode: '20140' },
          { name: 'โคกเพลาะ', postalCode: '20140' },
          { name: 'ไร่หลักทอง', postalCode: '20140' },
          { name: 'นามะตูม', postalCode: '20140' },
        ],
      },
      {
        name: 'ศรีราชา',
        subdistricts: [
          { name: 'ศรีราชา', postalCode: '20110' },
          { name: 'สุรศักดิ์', postalCode: '20110' },
          { name: 'ทุ่งสุขลา', postalCode: '20230' },
          { name: 'บึง', postalCode: '20230' },
          { name: 'หนองขาม', postalCode: '20110' },
          { name: 'เขาคันทรง', postalCode: '20110' },
          { name: 'บางพระ', postalCode: '20110' },
          { name: 'บ่อวิน', postalCode: '20230' },
        ],
      },
      {
        name: 'เกาะสีชัง',
        subdistricts: [
          { name: 'ท่าเทววงษ์', postalCode: '20120' },
        ],
      },
      {
        name: 'สัตหีบ',
        subdistricts: [
          { name: 'สัตหีบ', postalCode: '20180' },
          { name: 'นาจอมเทียน', postalCode: '20250' },
          { name: 'พลูตาหลวง', postalCode: '20180' },
          { name: 'บางเสร่', postalCode: '20250' },
          { name: 'แสมสาร', postalCode: '20180' },
        ],
      },
      {
        name: 'บ่อทอง',
        subdistricts: [
          { name: 'บ่อทอง', postalCode: '20270' },
          { name: 'วัดสุวรรณ', postalCode: '20270' },
          { name: 'บ่อกวางทอง', postalCode: '20270' },
          { name: 'ธาตุทอง', postalCode: '20270' },
          { name: 'เกษตรสุวรรณ', postalCode: '20270' },
          { name: 'พลวงทอง', postalCode: '20270' },
        ],
      },
      {
        name: 'เกาะจันทร์',
        subdistricts: [
          { name: 'เกาะจันทร์', postalCode: '20240' },
          { name: 'ท่าบุญมี', postalCode: '20240' },
        ],
      },
    ],
  },
  {
    name: 'สมุทรปราการ',
    districts: [
      {
        name: 'เมืองสมุทรปราการ',
        subdistricts: [
          { name: 'ปากน้ำ', postalCode: '10270' },
          { name: 'สำโรงเหนือ', postalCode: '10270' },
          { name: 'บางเมือง', postalCode: '10270' },
          { name: 'ท้ายบ้าน', postalCode: '10280' },
          { name: 'บางปูใหม่', postalCode: '10280' },
          { name: 'แพรกษา', postalCode: '10280' },
          { name: 'บางโปรง', postalCode: '10270' },
          { name: 'บางปู', postalCode: '10280' },
          { name: 'บางด้วน', postalCode: '10270' },
          { name: 'บางเมืองใหม่', postalCode: '10270' },
          { name: 'เทพารักษ์', postalCode: '10270' },
          { name: 'ท้ายบ้านใหม่', postalCode: '10280' },
          { name: 'แพรกษาใหม่', postalCode: '10280' },
        ],
      },
      {
        name: 'บางบ่อ',
        subdistricts: [
          { name: 'บางบ่อ', postalCode: '10560' },
          { name: 'บ้านระกาศ', postalCode: '10560' },
          { name: 'บางพลีน้อย', postalCode: '10560' },
          { name: 'บางเพรียง', postalCode: '10560' },
          { name: 'คลองด่าน', postalCode: '10550' },
          { name: 'คลองสวน', postalCode: '10560' },
          { name: 'เปร็ง', postalCode: '10560' },
          { name: 'คลองนิยมยาตรา', postalCode: '10560' },
        ],
      },
      {
        name: 'บางพลี',
        subdistricts: [
          { name: 'บางพลีใหญ่', postalCode: '10540' },
          { name: 'บางแก้ว', postalCode: '10540' },
          { name: 'บางปลา', postalCode: '10540' },
          { name: 'บางโฉลง', postalCode: '10540' },
          { name: 'ราชาเทวะ', postalCode: '10540' },
          { name: 'หนองปรือ', postalCode: '10540' },
        ],
      },
      {
        name: 'พระประแดง',
        subdistricts: [
          { name: 'ตลาด', postalCode: '10130' },
          { name: 'บางพึ่ง', postalCode: '10130' },
          { name: 'บางจาก', postalCode: '10130' },
          { name: 'บางครุ', postalCode: '10130' },
          { name: 'บางหญ้าแพรก', postalCode: '10130' },
          { name: 'บางหัวเสือ', postalCode: '10130' },
          { name: 'สำโรง', postalCode: '10130' },
          { name: 'สำโรงกลาง', postalCode: '10130' },
          { name: 'บางยอ', postalCode: '10130' },
          { name: 'บางกะเจ้า', postalCode: '10130' },
          { name: 'บางน้ำผึ้ง', postalCode: '10130' },
          { name: 'บางกระสอบ', postalCode: '10130' },
          { name: 'บางกอบัว', postalCode: '10130' },
          { name: 'ทรงคนอง', postalCode: '10130' },
          { name: 'สำโรงใต้', postalCode: '10130' },
        ],
      },
      {
        name: 'พระสมุทรเจดีย์',
        subdistricts: [
          { name: 'นาเกลือ', postalCode: '10290' },
          { name: 'บ้านคลองสวน', postalCode: '10290' },
          { name: 'แหลมฟ้าผ่า', postalCode: '10290' },
          { name: 'ปากคลองบางปลากด', postalCode: '10290' },
          { name: 'ในคลองบางปลากด', postalCode: '10290' },
        ],
      },
      {
        name: 'บางเสาธง',
        subdistricts: [
          { name: 'บางเสาธง', postalCode: '10570' },
          { name: 'ศีรษะจรเข้น้อย', postalCode: '10570' },
          { name: 'ศีรษะจรเข้ใหญ่', postalCode: '10570' },
        ],
      },
    ],
  },
  {
    name: 'นนทบุรี',
    districts: [
      {
        name: 'เมืองนนทบุรี',
        subdistricts: [
          { name: 'สวนใหญ่', postalCode: '11000' },
          { name: 'ตลาดขวัญ', postalCode: '11000' },
          { name: 'บางเขน', postalCode: '11000' },
          { name: 'บางกระสอ', postalCode: '11000' },
          { name: 'ท่าทราย', postalCode: '11000' },
          { name: 'บางไผ่', postalCode: '11000' },
          { name: 'บางศรีเมือง', postalCode: '11000' },
          { name: 'บางกร่าง', postalCode: '11000' },
          { name: 'ไทรม้า', postalCode: '11000' },
          { name: 'บางรักน้อย', postalCode: '11000' },
        ],
      },
      {
        name: 'บางกรวย',
        subdistricts: [
          { name: 'วัดชลอ', postalCode: '11130' },
          { name: 'บางกรวย', postalCode: '11130' },
          { name: 'บางสีทอง', postalCode: '11130' },
          { name: 'บางขนุน', postalCode: '11130' },
          { name: 'บางขุนกอง', postalCode: '11130' },
          { name: 'บางคูเวียง', postalCode: '11130' },
          { name: 'มหาสวัสดิ์', postalCode: '11130' },
          { name: 'ปลายบาง', postalCode: '11130' },
          { name: 'ศาลากลาง', postalCode: '11130' },
        ],
      },
      {
        name: 'บางใหญ่',
        subdistricts: [
          { name: 'บางใหญ่', postalCode: '11140' },
          { name: 'เสาธงหิน', postalCode: '11140' },
          { name: 'บางม่วง', postalCode: '11140' },
          { name: 'บางเลน', postalCode: '11140' },
          { name: 'บางแม่นาง', postalCode: '11140' },
          { name: 'บ้านใหม่', postalCode: '11140' },
        ],
      },
      {
        name: 'บางบัวทอง',
        subdistricts: [
          { name: 'โสนลอย', postalCode: '11110' },
          { name: 'บางบัวทอง', postalCode: '11110' },
          { name: 'บางรักใหญ่', postalCode: '11110' },
          { name: 'บางคูรัด', postalCode: '11110' },
          { name: 'ละหาร', postalCode: '11110' },
          { name: 'ลำโพ', postalCode: '11110' },
          { name: 'พิมลราช', postalCode: '11110' },
          { name: 'บางรักพัฒนา', postalCode: '11110' },
        ],
      },
      {
        name: 'ไทรน้อย',
        subdistricts: [
          { name: 'ไทรน้อย', postalCode: '11150' },
          { name: 'ราษฎร์นิยม', postalCode: '11150' },
          { name: 'หนองเพรางาย', postalCode: '11150' },
          { name: 'ไทรใหญ่', postalCode: '11150' },
          { name: 'ขุนศรี', postalCode: '11150' },
          { name: 'คลองขวาง', postalCode: '11150' },
          { name: 'ทวีวัฒนา', postalCode: '11150' },
        ],
      },
      {
        name: 'ปากเกร็ด',
        subdistricts: [
          { name: 'ปากเกร็ด', postalCode: '11120' },
          { name: 'บางตลาด', postalCode: '11120' },
          { name: 'บ้านใหม่', postalCode: '11120' },
          { name: 'บางพูด', postalCode: '11120' },
          { name: 'บางตะไนย์', postalCode: '11120' },
          { name: 'คลองพระอุดม', postalCode: '11120' },
          { name: 'ท่าอิฐ', postalCode: '11120' },
          { name: 'เกาะเกร็ด', postalCode: '11120' },
          { name: 'อ้อมเกร็ด', postalCode: '11120' },
          { name: 'คลองข่อย', postalCode: '11120' },
          { name: 'บางพลับ', postalCode: '11120' },
          { name: 'คลองเกลือ', postalCode: '11120' },
        ],
      },
    ],
  },
  {
    name: 'ปทุมธานี',
    districts: [
      {
        name: 'เมืองปทุมธานี',
        subdistricts: [
          { name: 'บางปรอก', postalCode: '12000' },
          { name: 'บ้านใหม่', postalCode: '12000' },
          { name: 'บ้านกลาง', postalCode: '12000' },
          { name: 'บ้านฉาง', postalCode: '12000' },
          { name: 'บ้านกระแชง', postalCode: '12000' },
          { name: 'บางขะแยง', postalCode: '12000' },
          { name: 'บางคูวัด', postalCode: '12000' },
          { name: 'บางหลวง', postalCode: '12000' },
          { name: 'บางเดื่อ', postalCode: '12000' },
          { name: 'บางพูน', postalCode: '12000' },
          { name: 'บางพูด', postalCode: '12000' },
          { name: 'บางกะดี', postalCode: '12000' },
          { name: 'สวนพริกไทย', postalCode: '12000' },
          { name: 'หลักหก', postalCode: '12000' },
        ],
      },
      {
        name: 'คลองหลวง',
        subdistricts: [
          { name: 'คลองหนึ่ง', postalCode: '12120' },
          { name: 'คลองสอง', postalCode: '12120' },
          { name: 'คลองสาม', postalCode: '12120' },
          { name: 'คลองสี่', postalCode: '12120' },
          { name: 'คลองห้า', postalCode: '12120' },
          { name: 'คลองหก', postalCode: '12120' },
          { name: 'คลองเจ็ด', postalCode: '12120' },
        ],
      },
      {
        name: 'ธัญบุรี',
        subdistricts: [
          { name: 'ประชาธิปัตย์', postalCode: '12130' },
          { name: 'บึงยี่โถ', postalCode: '12130' },
          { name: 'รังสิต', postalCode: '12110' },
          { name: 'ลำผักกูด', postalCode: '12110' },
          { name: 'บึงสนั่น', postalCode: '12110' },
          { name: 'บึงน้ำรักษ์', postalCode: '12110' },
        ],
      },
      {
        name: 'หนองเสือ',
        subdistricts: [
          { name: 'บึงบา', postalCode: '12170' },
          { name: 'บึงบอน', postalCode: '12170' },
          { name: 'บึงกาสาม', postalCode: '12170' },
          { name: 'บึงชำอ้อ', postalCode: '12170' },
          { name: 'หนองสามวัง', postalCode: '12170' },
          { name: 'ศาลาครุ', postalCode: '12170' },
          { name: 'นพรัตน์', postalCode: '12170' },
        ],
      },
      {
        name: 'ลาดหลุมแก้ว',
        subdistricts: [
          { name: 'ระแหง', postalCode: '12140' },
          { name: 'ลาดหลุมแก้ว', postalCode: '12140' },
          { name: 'คูบางหลวง', postalCode: '12140' },
          { name: 'คูขวาง', postalCode: '12140' },
          { name: 'คลองพระอุดม', postalCode: '12140' },
          { name: 'บ่อเงิน', postalCode: '12140' },
          { name: 'หน้าไม้', postalCode: '12140' },
        ],
      },
      {
        name: 'ลำลูกกา',
        subdistricts: [
          { name: 'คูคต', postalCode: '12130' },
          { name: 'ลาดสวาย', postalCode: '12150' },
          { name: 'บึงคำพร้อย', postalCode: '12150' },
          { name: 'ลำลูกกา', postalCode: '12150' },
          { name: 'บึงทองหลาง', postalCode: '12150' },
          { name: 'ลำไทร', postalCode: '12150' },
          { name: 'บึงคอไห', postalCode: '12150' },
          { name: 'พืชอุดม', postalCode: '12150' },
        ],
      },
      {
        name: 'สามโคก',
        subdistricts: [
          { name: 'บางเตย', postalCode: '12160' },
          { name: 'คลองควาย', postalCode: '12160' },
          { name: 'สามโคก', postalCode: '12160' },
          { name: 'กระแชง', postalCode: '12160' },
          { name: 'บางกระบือ', postalCode: '12160' },
          { name: 'ท้ายเกาะ', postalCode: '12160' },
          { name: 'บ้านงิ้ว', postalCode: '12160' },
          { name: 'เชียงรากใหญ่', postalCode: '12160' },
          { name: 'บ้านปทุม', postalCode: '12160' },
          { name: 'บ้านนา', postalCode: '12160' },
          { name: 'เชียงรากน้อย', postalCode: '12160' },
        ],
      },
    ],
  },
  {
    name: 'ภูเก็ต',
    districts: [
      {
        name: 'เมืองภูเก็ต',
        subdistricts: [
          { name: 'ตลาดใหญ่', postalCode: '83000' },
          { name: 'ตลาดเหนือ', postalCode: '83000' },
          { name: 'เกาะแก้ว', postalCode: '83000' },
          { name: 'รัษฎา', postalCode: '83000' },
          { name: 'วิชิต', postalCode: '83000' },
          { name: 'ฉลอง', postalCode: '83130' },
          { name: 'ราไวย์', postalCode: '83130' },
          { name: 'กะรน', postalCode: '83100' },
        ],
      },
      {
        name: 'กะทู้',
        subdistricts: [
          { name: 'กะทู้', postalCode: '83120' },
          { name: 'ป่าตอง', postalCode: '83150' },
          { name: 'กมลา', postalCode: '83150' },
        ],
      },
      {
        name: 'ถลาง',
        subdistricts: [
          { name: 'เทพกระษัตรี', postalCode: '83110' },
          { name: 'ศรีสุนทร', postalCode: '83110' },
          { name: 'เชิงทะเล', postalCode: '83110' },
          { name: 'ป่าคลอก', postalCode: '83110' },
          { name: 'ไม้ขาว', postalCode: '83110' },
          { name: 'สาคู', postalCode: '83110' },
        ],
      },
    ],
  },
  {
    name: 'สงขลา',
    districts: [
      {
        name: 'เมืองสงขลา',
        subdistricts: [
          { name: 'บ่อยาง', postalCode: '90000' },
          { name: 'เขารูปช้าง', postalCode: '90000' },
          { name: 'เกาะแต้ว', postalCode: '90000' },
          { name: 'พะวง', postalCode: '90100' },
          { name: 'ทุ่งหวัง', postalCode: '90000' },
          { name: 'เกาะยอ', postalCode: '90100' },
        ],
      },
      {
        name: 'สทิงพระ',
        subdistricts: [
          { name: 'จะทิ้งพระ', postalCode: '90190' },
          { name: 'กระดังงา', postalCode: '90190' },
          { name: 'สนามชัย', postalCode: '90190' },
          { name: 'ดีหลวง', postalCode: '90190' },
          { name: 'ชุมพล', postalCode: '90190' },
          { name: 'คลองรี', postalCode: '90190' },
          { name: 'คูขุด', postalCode: '90190' },
          { name: 'ท่าหิน', postalCode: '90190' },
          { name: 'วัดจันทร์', postalCode: '90190' },
          { name: 'บ่อแดง', postalCode: '90190' },
          { name: 'บ่อดาน', postalCode: '90190' },
        ],
      },
      {
        name: 'จะนะ',
        subdistricts: [
          { name: 'บ้านนา', postalCode: '90130' },
          { name: 'ป่าชิง', postalCode: '90130' },
          { name: 'สะพานไม้แก่น', postalCode: '90130' },
          { name: 'สะกอม', postalCode: '90130' },
          { name: 'นาหว้า', postalCode: '90130' },
          { name: 'นาทับ', postalCode: '90130' },
          { name: 'น้ำขาว', postalCode: '90130' },
          { name: 'ขุนตัดหวาย', postalCode: '90130' },
          { name: 'ท่าหมอไทร', postalCode: '90130' },
          { name: 'จะโหนง', postalCode: '90130' },
          { name: 'คู', postalCode: '90130' },
          { name: 'แค', postalCode: '90130' },
          { name: 'คลองเปียะ', postalCode: '90130' },
          { name: 'ตลิ่งชัน', postalCode: '90130' },
        ],
      },
      {
        name: 'นาทวี',
        subdistricts: [
          { name: 'นาทวี', postalCode: '90160' },
          { name: 'ฉาง', postalCode: '90160' },
          { name: 'นาหมอศรี', postalCode: '90160' },
          { name: 'สะท้อน', postalCode: '90160' },
          { name: 'ท่าประดู่', postalCode: '90160' },
          { name: 'ปลักหนู', postalCode: '90160' },
          { name: 'ประกอบ', postalCode: '90160' },
          { name: 'คลองทราย', postalCode: '90160' },
          { name: 'คลองกวาง', postalCode: '90160' },
          { name: 'ทับช้าง', postalCode: '90160' },
        ],
      },
      {
        name: 'เทพา',
        subdistricts: [
          { name: 'เทพา', postalCode: '90150' },
          { name: 'ปากบาง', postalCode: '90150' },
          { name: 'เกาะสะบ้า', postalCode: '90150' },
          { name: 'ลำไพล', postalCode: '90260' },
          { name: 'ท่าม่วง', postalCode: '90150' },
          { name: 'วังใหญ่', postalCode: '90260' },
          { name: 'สะกอม', postalCode: '90150' },
        ],
      },
      {
        name: 'สะบ้าย้อย',
        subdistricts: [
          { name: 'สะบ้าย้อย', postalCode: '90210' },
          { name: 'ทุ่งพอ', postalCode: '90210' },
          { name: 'เปียน', postalCode: '90210' },
          { name: 'บ้านโหนด', postalCode: '90210' },
          { name: 'จะแหน', postalCode: '90210' },
          { name: 'คูหา', postalCode: '90210' },
          { name: 'เขาแดง', postalCode: '90210' },
          { name: 'บาโหย', postalCode: '90210' },
          { name: 'ธารคีรี', postalCode: '90210' },
        ],
      },
      {
        name: 'ระโนด',
        subdistricts: [
          { name: 'ระโนด', postalCode: '90140' },
          { name: 'คลองแดน', postalCode: '90140' },
          { name: 'ตะเครียะ', postalCode: '90140' },
          { name: 'ท่าบอน', postalCode: '90140' },
          { name: 'บ้านใหม่', postalCode: '90140' },
          { name: 'บ่อตรุ', postalCode: '90140' },
          { name: 'ปากแตระ', postalCode: '90140' },
          { name: 'พังยาง', postalCode: '90140' },
          { name: 'ระวะ', postalCode: '90140' },
          { name: 'วัดสน', postalCode: '90140' },
          { name: 'บ้านขาว', postalCode: '90140' },
          { name: 'แดนสงวน', postalCode: '90140' },
        ],
      },
      {
        name: 'กระแสสินธุ์',
        subdistricts: [
          { name: 'เกาะใหญ่', postalCode: '90270' },
          { name: 'โรง', postalCode: '90270' },
          { name: 'เชิงแส', postalCode: '90270' },
          { name: 'กระแสสินธุ์', postalCode: '90270' },
        ],
      },
      {
        name: 'รัตภูมิ',
        subdistricts: [
          { name: 'กำแพงเพชร', postalCode: '90180' },
          { name: 'ท่าชะมวง', postalCode: '90180' },
          { name: 'คูหาใต้', postalCode: '90180' },
          { name: 'ควนรู', postalCode: '90180' },
          { name: 'เขาพระ', postalCode: '90180' },
        ],
      },
      {
        name: 'สะเดา',
        subdistricts: [
          { name: 'สะเดา', postalCode: '90120' },
          { name: 'ปริก', postalCode: '90120' },
          { name: 'พังลา', postalCode: '90170' },
          { name: 'สำนักแต้ว', postalCode: '90120' },
          { name: 'ทุ่งหมอ', postalCode: '90240' },
          { name: 'ท่าโพธิ์', postalCode: '90170' },
          { name: 'ปาดังเบซาร์', postalCode: '90240' },
          { name: 'สำนักขาม', postalCode: '90320' },
          { name: 'เขามีเกียรติ', postalCode: '90170' },
        ],
      },
      {
        name: 'หาดใหญ่',
        subdistricts: [
          { name: 'หาดใหญ่', postalCode: '90110' },
          { name: 'ควนลัง', postalCode: '90110' },
          { name: 'คูเต่า', postalCode: '90110' },
          { name: 'คอหงส์', postalCode: '90110' },
          { name: 'คลองแห', postalCode: '90110' },
          { name: 'คลองอู่ตะเภา', postalCode: '90110' },
          { name: 'ฉลุง', postalCode: '90110' },
          { name: 'ทุ่งใหญ่', postalCode: '90110' },
          { name: 'ทุ่งตำเสา', postalCode: '90110' },
          { name: 'ท่าข้าม', postalCode: '90110' },
          { name: 'น้ำน้อย', postalCode: '90110' },
          { name: 'บ้านพรุ', postalCode: '90250' },
          { name: 'พะตง', postalCode: '90230' },
        ],
      },
      {
        name: 'นาหม่อม',
        subdistricts: [
          { name: 'นาหม่อม', postalCode: '90310' },
          { name: 'พิจิตร', postalCode: '90310' },
          { name: 'ทุ่งขมิ้น', postalCode: '90310' },
          { name: 'คลองหรัง', postalCode: '90310' },
        ],
      },
      {
        name: 'ควนเนียง',
        subdistricts: [
          { name: 'รัตภูมิ', postalCode: '90220' },
          { name: 'ควนโส', postalCode: '90220' },
          { name: 'ห้วยลึก', postalCode: '90220' },
          { name: 'บางเหรียง', postalCode: '90220' },
        ],
      },
      {
        name: 'บางกล่ำ',
        subdistricts: [
          { name: 'บางกล่ำ', postalCode: '90110' },
          { name: 'ท่าช้าง', postalCode: '90110' },
          { name: 'แม่ทอม', postalCode: '90110' },
          { name: 'บ้านหาร', postalCode: '90110' },
        ],
      },
      {
        name: 'สิงหนคร',
        subdistricts: [
          { name: 'ชิงโค', postalCode: '90280' },
          { name: 'สทิงหม้อ', postalCode: '90280' },
          { name: 'ทำนบ', postalCode: '90280' },
          { name: 'รำแดง', postalCode: '90330' },
          { name: 'วัดขนุน', postalCode: '90330' },
          { name: 'ชะแล้', postalCode: '90330' },
          { name: 'ปากรอ', postalCode: '90330' },
          { name: 'ป่าขาด', postalCode: '90330' },
          { name: 'หัวเขา', postalCode: '90280' },
          { name: 'บางเขียด', postalCode: '90330' },
          { name: 'ม่วงงาม', postalCode: '90330' },
        ],
      },
      {
        name: 'คลองหอยโข่ง',
        subdistricts: [
          { name: 'คลองหอยโข่ง', postalCode: '90230' },
          { name: 'ทุ่งลาน', postalCode: '90230' },
          { name: 'โคกม่วง', postalCode: '90230' },
          { name: 'คลองหลา', postalCode: '90115' },
        ],
      },
    ],
  },
  { name: 'กระบี่', districts: [{ name: 'เมืองกระบี่', subdistricts: [{ name: 'ปากน้ำ', postalCode: '81000' }] }] },
  { name: 'กาญจนบุรี', districts: [{ name: 'เมืองกาญจนบุรี', subdistricts: [{ name: 'บ้านเหนือ', postalCode: '71000' }] }] },
  { name: 'กาฬสินธุ์', districts: [{ name: 'เมืองกาฬสินธุ์', subdistricts: [{ name: 'กาฬสินธุ์', postalCode: '46000' }] }] },
  { name: 'กำแพงเพชร', districts: [{ name: 'เมืองกำแพงเพชร', subdistricts: [{ name: 'ในเมือง', postalCode: '62000' }] }] },
  { name: 'จันทบุรี', districts: [{ name: 'เมืองจันทบุรี', subdistricts: [{ name: 'ตลาด', postalCode: '22000' }] }] },
  { name: 'ฉะเชิงเทรา', districts: [{ name: 'เมืองฉะเชิงเทรา', subdistricts: [{ name: 'หน้าเมือง', postalCode: '24000' }] }] },
  { name: 'ชัยนาท', districts: [{ name: 'เมืองชัยนาท', subdistricts: [{ name: 'ในเมือง', postalCode: '17000' }] }] },
  { name: 'ชัยภูมิ', districts: [{ name: 'เมืองชัยภูมิ', subdistricts: [{ name: 'ในเมือง', postalCode: '36000' }] }] },
  { name: 'ชุมพร', districts: [{ name: 'เมืองชุมพร', subdistricts: [{ name: 'ท่าตะเภา', postalCode: '86000' }] }] },
  { name: 'เชียงราย', districts: [{ name: 'เมืองเชียงราย', subdistricts: [{ name: 'เวียง', postalCode: '57000' }] }] },
  { name: 'ตรัง', districts: [{ name: 'เมืองตรัง', subdistricts: [{ name: 'ทับเที่ยง', postalCode: '92000' }] }] },
  { name: 'ตราด', districts: [{ name: 'เมืองตราด', subdistricts: [{ name: 'บางพระ', postalCode: '23000' }] }] },
  { name: 'ตาก', districts: [{ name: 'เมืองตาก', subdistricts: [{ name: 'ระแหง', postalCode: '63000' }] }] },
  { name: 'นครนายก', districts: [{ name: 'เมืองนครนายก', subdistricts: [{ name: 'นครนายก', postalCode: '26000' }] }] },
  { name: 'นครปฐม', districts: [{ name: 'เมืองนครปฐม', subdistricts: [{ name: 'พระปฐมเจดีย์', postalCode: '73000' }] }] },
  { name: 'นครพนม', districts: [{ name: 'เมืองนครพนม', subdistricts: [{ name: 'ในเมือง', postalCode: '48000' }] }] },
  { name: 'นครศรีธรรมราช', districts: [{ name: 'เมืองนครศรีธรรมราช', subdistricts: [{ name: 'คลัง', postalCode: '80000' }] }] },
  { name: 'นครสวรรค์', districts: [{ name: 'เมืองนครสวรรค์', subdistricts: [{ name: 'ปากน้ำโพ', postalCode: '60000' }] }] },
  { name: 'นราธิวาส', districts: [{ name: 'เมืองนราธิวาส', subdistricts: [{ name: 'บางนาค', postalCode: '96000' }] }] },
  { name: 'น่าน', districts: [{ name: 'เมืองน่าน', subdistricts: [{ name: 'ในเมือง', postalCode: '55000' }] }] },
  { name: 'บึงกาฬ', districts: [{ name: 'เมืองบึงกาฬ', subdistricts: [{ name: 'บึงกาฬ', postalCode: '38000' }] }] },
  { name: 'บุรีรัมย์', districts: [{ name: 'เมืองบุรีรัมย์', subdistricts: [{ name: 'ในเมือง', postalCode: '31000' }] }] },
  { name: 'ประจวบคีรีขันธ์', districts: [{ name: 'เมืองประจวบคีรีขันธ์', subdistricts: [{ name: 'ประจวบคีรีขันธ์', postalCode: '77000' }] }] },
  { name: 'ปราจีนบุรี', districts: [{ name: 'เมืองปราจีนบุรี', subdistricts: [{ name: 'หน้าเมือง', postalCode: '25000' }] }] },
  { name: 'ปัตตานี', districts: [{ name: 'เมืองปัตตานี', subdistricts: [{ name: 'สะบารัง', postalCode: '94000' }] }] },
  { name: 'พระนครศรีอยุธยา', districts: [{ name: 'พระนครศรีอยุธยา', subdistricts: [{ name: 'ประตูชัย', postalCode: '13000' }] }] },
  { name: 'พะเยา', districts: [{ name: 'เมืองพะเยา', subdistricts: [{ name: 'เวียง', postalCode: '56000' }] }] },
  { name: 'พังงา', districts: [{ name: 'เมืองพังงา', subdistricts: [{ name: 'ท้ายช้าง', postalCode: '82000' }] }] },
  { name: 'พัทลุง', districts: [{ name: 'เมืองพัทลุง', subdistricts: [{ name: 'คูหาสวรรค์', postalCode: '93000' }] }] },
  { name: 'พิจิตร', districts: [{ name: 'เมืองพิจิตร', subdistricts: [{ name: 'ในเมือง', postalCode: '66000' }] }] },
  { name: 'พิษณุโลก', districts: [{ name: 'เมืองพิษณุโลก', subdistricts: [{ name: 'ในเมือง', postalCode: '65000' }] }] },
  { name: 'เพชรบุรี', districts: [{ name: 'เมืองเพชรบุรี', subdistricts: [{ name: 'คลองกระแชง', postalCode: '76000' }] }] },
  { name: 'เพชรบูรณ์', districts: [{ name: 'เมืองเพชรบูรณ์', subdistricts: [{ name: 'ในเมือง', postalCode: '67000' }] }] },
  { name: 'แพร่', districts: [{ name: 'เมืองแพร่', subdistricts: [{ name: 'ในเมือง', postalCode: '54000' }] }] },
  { name: 'มหาสารคาม', districts: [{ name: 'เมืองมหาสารคาม', subdistricts: [{ name: 'ตลาด', postalCode: '44000' }] }] },
  { name: 'มุกดาหาร', districts: [{ name: 'เมืองมุกดาหาร', subdistricts: [{ name: 'มุกดาหาร', postalCode: '49000' }] }] },
  { name: 'แม่ฮ่องสอน', districts: [{ name: 'เมืองแม่ฮ่องสอน', subdistricts: [{ name: 'จองคำ', postalCode: '58000' }] }] },
  { name: 'ยโสธร', districts: [{ name: 'เมืองยโสธร', subdistricts: [{ name: 'ในเมือง', postalCode: '35000' }] }] },
  { name: 'ยะลา', districts: [{ name: 'เมืองยะลา', subdistricts: [{ name: 'สะเตง', postalCode: '95000' }] }] },
  { name: 'ร้อยเอ็ด', districts: [{ name: 'เมืองร้อยเอ็ด', subdistricts: [{ name: 'ในเมือง', postalCode: '45000' }] }] },
  { name: 'ระนอง', districts: [{ name: 'เมืองระนอง', subdistricts: [{ name: 'เขานิเวศน์', postalCode: '85000' }] }] },
  { name: 'ระยอง', districts: [{ name: 'เมืองระยอง', subdistricts: [{ name: 'ท่าประดู่', postalCode: '21000' }] }] },
  { name: 'ราชบุรี', districts: [{ name: 'เมืองราชบุรี', subdistricts: [{ name: 'หน้าเมือง', postalCode: '70000' }] }] },
  { name: 'ลพบุรี', districts: [{ name: 'เมืองลพบุรี', subdistricts: [{ name: 'ท่าหิน', postalCode: '15000' }] }] },
  { name: 'ลำปาง', districts: [{ name: 'เมืองลำปาง', subdistricts: [{ name: 'หัวเวียง', postalCode: '52000' }] }] },
  { name: 'ลำพูน', districts: [{ name: 'เมืองลำพูน', subdistricts: [{ name: 'ในเมือง', postalCode: '51000' }] }] },
  { name: 'เลย', districts: [{ name: 'เมืองเลย', subdistricts: [{ name: 'กุดป่อง', postalCode: '42000' }] }] },
  { name: 'ศรีสะเกษ', districts: [{ name: 'เมืองศรีสะเกษ', subdistricts: [{ name: 'เมืองเหนือ', postalCode: '33000' }] }] },
  { name: 'สกลนคร', districts: [{ name: 'เมืองสกลนคร', subdistricts: [{ name: 'ธาตุเชิงชุม', postalCode: '47000' }] }] },
  { name: 'สตูล', districts: [{ name: 'เมืองสตูล', subdistricts: [{ name: 'พิมาน', postalCode: '91000' }] }] },
  { name: 'สมุทรสงคราม', districts: [{ name: 'เมืองสมุทรสงคราม', subdistricts: [{ name: 'แม่กลอง', postalCode: '75000' }] }] },
  { name: 'สมุทรสาคร', districts: [{ name: 'เมืองสมุทรสาคร', subdistricts: [{ name: 'มหาชัย', postalCode: '74000' }] }] },
  { name: 'สระแก้ว', districts: [{ name: 'เมืองสระแก้ว', subdistricts: [{ name: 'สระแก้ว', postalCode: '27000' }] }] },
  { name: 'สระบุรี', districts: [{ name: 'เมืองสระบุรี', subdistricts: [{ name: 'ปากเพรียว', postalCode: '18000' }] }] },
  { name: 'สิงห์บุรี', districts: [{ name: 'เมืองสิงห์บุรี', subdistricts: [{ name: 'บางพุทรา', postalCode: '16000' }] }] },
  { name: 'สุโขทัย', districts: [{ name: 'เมืองสุโขทัย', subdistricts: [{ name: 'ธานี', postalCode: '64000' }] }] },
  { name: 'สุพรรณบุรี', districts: [{ name: 'เมืองสุพรรณบุรี', subdistricts: [{ name: 'ท่าพี่เลี้ยง', postalCode: '72000' }] }] },
  { name: 'สุราษฎร์ธานี', districts: [{ name: 'เมืองสุราษฎร์ธานี', subdistricts: [{ name: 'ตลาด', postalCode: '84000' }] }] },
  { name: 'สุรินทร์', districts: [{ name: 'เมืองสุรินทร์', subdistricts: [{ name: 'ในเมือง', postalCode: '32000' }] }] },
  { name: 'หนองคาย', districts: [{ name: 'เมืองหนองคาย', subdistricts: [{ name: 'ในเมือง', postalCode: '43000' }] }] },
  { name: 'หนองบัวลำภู', districts: [{ name: 'เมืองหนองบัวลำภู', subdistricts: [{ name: 'หนองบัว', postalCode: '39000' }] }] },
  { name: 'อ่างทอง', districts: [{ name: 'เมืองอ่างทอง', subdistricts: [{ name: 'ตลาดหลวง', postalCode: '14000' }] }] },
  { name: 'อำนาจเจริญ', districts: [{ name: 'เมืองอำนาจเจริญ', subdistricts: [{ name: 'บุ่ง', postalCode: '37000' }] }] },
  { name: 'อุดรธานี', districts: [{ name: 'เมืองอุดรธานี', subdistricts: [{ name: 'หมากแข้ง', postalCode: '41000' }] }] },
  { name: 'อุตรดิตถ์', districts: [{ name: 'เมืองอุตรดิตถ์', subdistricts: [{ name: 'ท่าอิฐ', postalCode: '53000' }] }] },
  { name: 'อุทัยธานี', districts: [{ name: 'เมืองอุทัยธานี', subdistricts: [{ name: 'อุทัยใหม่', postalCode: '61000' }] }] },
  { name: 'อุบลราชธานี', districts: [{ name: 'เมืองอุบลราชธานี', subdistricts: [{ name: 'ในเมือง', postalCode: '34000' }] }] },
];

// Helper functions
export function getProvinces(): string[] {
  return thaiAddressData.map(p => p.name);
}

export function getDistrictsByProvince(provinceName: string): string[] {
  const province = thaiAddressData.find(p => p.name === provinceName);
  return province ? province.districts.map(d => d.name) : [];
}

export function getSubdistrictsByDistrict(provinceName: string, districtName: string): Subdistrict[] {
  const province = thaiAddressData.find(p => p.name === provinceName);
  if (!province) return [];

  const district = province.districts.find(d => d.name === districtName);
  return district ? district.subdistricts : [];
}

export function getPostalCodeBySubdistrict(provinceName: string, districtName: string, subdistrictName: string): string {
  const subdistricts = getSubdistrictsByDistrict(provinceName, districtName);
  const subdistrict = subdistricts.find(s => s.name === subdistrictName);
  return subdistrict ? subdistrict.postalCode : '';
}
